name: guard
version: 1.0.2
description: Evauluates the function wrapping the body with try/catch and returns default value if error was raised
homepage: https://github.com/lesnitsky/guard

environment:
  sdk: ">=2.7.0 <3.0.0"
